name: musify_mobile
description: My cource project

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #Dart packages
  equatable: ^2.0.5
  get_it: ^7.2.0
  dio: ^4.0.6
  intl: ^0.17.0

  #Flutter packages
  auto_route: ^5.0.4
  shared_preferences: ^2.0.17
  flutter_bloc: ^8.1.0
  cached_network_image: ^3.2.3
  provider: ^6.0.5
  drift: ^2.4.2
  path_provider: ^2.0.12
  url_launcher: ^6.1.8
  file_picker: ^5.2.5
  just_audio: ^0.9.31

  #Platform plugins
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test:
  build_runner:
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/images/

