name: musify_mobile
description: My cource project

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #Dart packages
  equatable: ^2.0.3
  get_it: ^7.2.0
  dio: ^4.0.1
  intl: ^0.17.0

  #Flutter packages
  auto_route: ^3.2.4
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.0.0
  cached_network_image: ^3.2.0
  line_icons: ^2.0.1
  provider: ^6.0.2
  hive_flutter: ^1.1.0
  path_provider: ^2.0.8
  url_launcher: ^6.0.18
  file_picker: ^4.5.1
  just_audio: ^0.9.21
  sqflite: ^2.0.0+3
  
  #Platform plugins
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.0.1
  bloc_test: ^9.0.1
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

